<?php

return array
(
    'ID_C_TIPO_TRAMITE_CITA_LINEA' => env('ID_C_TIPO_TRAMITE_CITA_LINEA'),
    'ID_C_TIPO_CONSULTA' => env('ID_C_TIPO_CONSULTA'),
    'ID_HORARIO_CITAS' => env('ID_HORARIO_CITAS'),

    'ID_CI_ESCRITURA_PUBLICA' => env('ID_CI_ESCRITURA_PUBLICA'),
    'ID_CI_CONSULTA_PROTOCOLO' => env('ID_CI_CONSULTA_PROTOCOLO'),
    'ID_CI_SECCION_DE_TIERRAS' => env('ID_CI_SECCION_DE_TIERRAS'),
    'ID_CI_ARCHIVO_HISTORICO' => env('ID_CI_ARCHIVO_HISTORICO'),

    'ID_CI_SOLICITUD_PROTOCOLO' => env('ID_CI_SOLICITUD_PROTOCOLO'),
);

